# Generated by Django 5.2.6 on 2025-09-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='comleted',
            new_name='completed',
        ),
    ]
